### ISSUE TITLE
Features list compared to MaiB

### ISSUE THREAD

**Issue by so0k** [indiehosters/email#1]
Not sure if this has been outlined in a readme or wiki somewhere, sorry for asking if it is.

How do the features compare to MaiB?

**Comment by pierreozoux** [comment]
I updated the README to be closer to miab presentation.
I opened 3 issues to let people know about the feature I plan to add.

I don't plan to add ownCloud, DNS or nginx as it is already part of the IndieHosters paper (DNS not yet, but it is the plan).
But I'd be happy to make this converge to maib (then, I'd remove the unnecessary component for me)

If it is clear enough, please close the issue :)

Thanks!

**Comment by so0k** [comment]
Thanks for update, I just tried to put it side by side quickly, maybe I got some stuff wrong?

seems TODOs don't work in a table :(
- [ ] test1
- [x] test2

| indiehosters/email | mail-in-a-box/mailinabox | status |
| --- | --- | --- |
| [x] SMTP (postfix) | [x] SMTP (postfix) | :white_check_mark: |
| [x] IMAP (dovecot) | [x] IMAP (dovecot) | :white_check_mark: |
| [ ] search (dovecot-lucene) | [x] search (dovecot-lucene) | [planned](https://github.com/indiehosters/email/issues/5) |
| [ ] CardDAV/CalDAV (ownCloud) | [x] CardDAV/CalDAV (ownCloud) | part of other package |
| [ ] Exchange ActiveSync (z-push) | [x] Exchange ActiveSync (z-push) | [planned](https://github.com/indiehosters/email/issues/3) |
| [ ] Webmail (Roundcube) | [x] Webmail (Roundcube) | [planned](https://github.com/indiehosters/email/issues/4) |
| [ ] static website hosting (nginx) | [x] static website hosting (nginx) | part of other package |
| [ ] Spam filtering (spamassassin) | [x] Spam filtering (spamassassin) | [planned](https://github.com/indiehosters/email/issues/2) |
| [x] greylisting (postgrey) | [x] greylisting (postgrey) | :white_check_mark: |
| [ ] Backups (duplicity) | [x] Backups (duplicity) | part of [backup](https://github.com/IndiePaaS/IndiePaaS/blob/master/unit-files/b-u%40.service) package |
| [ ] firewall (ufw) | [x] firewall (ufw) | planned, as part of [firewall](https://github.com/IndiePaaS/IndiePaaS/issues/108) package |
| [ ] intrusion protection (fail2ban) | [x] intrusion protection (fail2ban) | ? (difficult in docker) |
| [ ] system monitoring (munin) | [x] system monitoring (munin) | planned, as part of other package |

DNS (nsd4):

| indiehosters/email | mail-in-a-box/mailinabox | status |
| --- | --- | --- |
| [x] DKIM (OpenDKIM) | [x] DKIM (OpenDKIM) | :white_check_mark: |
| [x] DMARC | [x] DMARC (postgrey) | :white_check_mark: |
| [ ] SPF | [x] SPF | planned, as part of [DNS](https://github.com/IndiePaaS/IndiePaaS/issues/98) |
| [ ] DNSSEC | [x] DNSSEC | planned, as part of [DNS](https://github.com/IndiePaaS/IndiePaaS/issues/98) |
| [ ] DANE TLSA | [x] DANE TLSA | planned, as part of [DNS](https://github.com/IndiePaaS/IndiePaaS/issues/98) |
| [ ] SSHFP records | [x] SSHFP records | planned, as part of [DNS](https://github.com/IndiePaaS/IndiePaaS/issues/98) |

control panel and API:

| indiehosters/email | mail-in-a-box/mailinabox | status |
| --- | --- | --- |
| [x] vimbadmin | [x] custom coded | :white_check_mark: |
| [x] Add/Remove mail User | [x] Add/Remove mail User | :white_check_mark: |
| [x] Add/Remove Aliases | [x] Add/Remove Aliases | :white_check_mark: |
| [ ] custom DNS records | [x] custom DNS records | planned, as part of [DNS](https://github.com/IndiePaaS/IndiePaaS/issues/98) |
| [x] multiadmin | [ ] mutliadmin | :white_check_mark: |

**Comment by so0k** [comment]
also, what I wonder sometimes is - how do these things compare to cPanel / Sentora? I first set up a MaiB, but a friend of mine is using cPanel... perhaps the TLS / secure webmail is better handled by MaiB? (sorry to take this issue off topic)

**Comment by pierreozoux** [comment]
Thanks for your comment! I'll update the README :)

I would say miab focus on one email system for a personal use, and they do it really well! But they target sysadmin (or people not afraid of running a coomand line)
cPanel is no free software.
I didn't know Sentora, I added to my list :) Thanks!

The plan for IndieHosters is to provide free software as a service. For now, we are still on polishing the backend part. How we orchestrate containers to provide a really nice PaaS for shared hosting. Then, we plan on working on a nice UI, or maybe reusing UI out there, like Sentora or [clouder](https://www.goclouder.net/) :)

**Comment by pierreozoux** [comment]
Thanks a lot! Can I close the issue?

**Comment by so0k** [comment]
sorry, I meant "zPanel" - Sentora is the new version of zPanel.
