### ISSUE TITLE
Add spamassasin

### ISSUE THREAD

**Issue by pierreozoux** [indiehosters/email#2]

**Comment by pbouda** [comment]
I added a first version with working spamassassin :-) It's heavily based in the mailinabox setup, which means some things changed:
- dovecot: added sieve plugin, all messages that have a threshold above 5.0 from spamassassin are moved to the "Spam" folder. sieve can also be used by our users to set rules for incoming mails (not well tested atm).
- dovecot: uses now the default folders from mailinabox (see https://github.com/indiehosters/docker-dovecot/blob/spamassassin/15-mailboxes.conf).

The changes are in the branches "spamassassin" of email, postfix and dovecot, plus the new docker-spamassassin. Please have a look and give comments, then I will merge everything.
