### ISSUE TITLE
syslogdev from local directory not working for me

### ISSUE THREAD

**Issue by djmaze** [indiehosters/email#8]
When trying to start the syslog container, I get the following error message:

```
Cannot start container 89a2c55c6e8c33223f53df942a278841451d212d1a0bc00e011e4324981b4253: [8] System error: Failed to open /dev/null - open /dev/null: permission denied'
```

I have to change `./tmp/syslogdev` to `/tmp/syslogdev` in docker-compose.yml order to get it working. Is this working for you, @pierreozoux?

(I am running docker via sudo, btw.)

**Comment by pierreozoux** [comment]
I didn't get any issue with that.
Are you running on linux (or win/Mac though a VM?)

**Comment by djmaze** [comment]
Yes, on my local Linux machine. I will try on another one.

**Comment by pierreozoux** [comment]
We did a quiet big refactor (mainly to move out the dockerfiles to separate repos) and so, the result is that we mount local /dev/log from the host.
https://github.com/indiehosters/email/commit/5b0721933e6ce1e0412b3c231d7e514cadf0c7b3

I know, it is not the most beautiful, but if you have a better option, please let me know :)

**Comment by djmaze** [comment]
Ok, cool. Thumbsup for the refactor! Will try that out.

Although I still don't like the mixing of postfix and opend{marc,kim} in the same container. The improved support for Docker networking in the new Docker Compose version will finally allow doing away with links and using [small, well-defined networks instead](https://blog.docker.com/2016/02/compose-1-6/).

**Comment by pierreozoux** [comment]
I don't like neither :/

Thanks for the article, I spotted it a bit earlier the same day ;)
Indeed exciting time!

On 10-02-2016 20:57, Martin Honermeyer wrote:

> Ok, cool. Thumbsup for the refactor! Will try that out.
> 
> Although I still don't like the mixing of postfix and opend{marc,kim} in the same container. The improved support for Docker networking in the new Docker Compose version will finally allow doing away with links and using [small, well-defined networks instead](https://blog.docker.com/2016/02/compose-1-6/).
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/indiehosters/email/issues/8#issuecomment-182579445

## 

I use PGP to protect our privacy, if you want to know more, you can
follow this
https://emailselfdefense.fsf.org/en/

If you have further questions, please do not hesitate to ask.
You can verify my public key here: https://keybase.io/pierreozoux
